### ISSUE TITLE
Adapt diffrent time formats from host

### ISSUE THREAD

**Issue by mnokka** [mnokka/JiraPluginInfo#4]
Currently cant hadnle following timeformat from host jira:

2019-03-05 10:04:19,594:GetInfo.py:INFO:EXPIRATION DATE:25.10.2020
Traceback (most recent call last):
  File "GetInfo.py", line 332, in <module>
    main(sys.argv[1:])
  File "GetInfo.py", line 115, in main
    GetStepInfo(jira,JIRASERVICE,user,PASSWORD,DEBUG,logger,THRDAYS,DEVDEBUG)    
  File "GetInfo.py", line 236, in GetStepInfo
    Converdate = datetime.datetime.strptime(ExpDate, '%d/%b/%y')
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '25.10.2020' does not match format '%d/%b/%y'

**Comment by mnokka** [comment]
Current expected input: EXPIRATION DATE:23/Oct/18

**Comment by mnokka** [comment]
first solution found
